### ISSUE TITLE
Rails 5.1.0.beta1: scaffold generator error

### ISSUE THREAD

**Issue by cerdiogenes** [indirect/haml-rails#122]
When I run `rails g scaffold foo name:string` I get the following stack trace:

```
/usr/local/bundle/gems/railties-5.1.0.beta1/lib/rails/generators/erb.rb:20:in `filename_with_extensions': private method `format' called for #<Haml::Generators::ScaffoldGenerator:0x00557f14c0b7a8> (NoMethodError)
	from /usr/local/bundle/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/scaffold_generator.rb:10:in `block in copy_view_files'
	from /usr/local/bundle/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/scaffold_generator.rb:9:in `each'
	from /usr/local/bundle/gems/haml-rails-0.9.0/lib/generators/haml/scaffold/scaffold_generator.rb:9:in `copy_view_files'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/bundle/gems/railties-5.1.0.beta1/lib/rails/generators/rails/scaffold_controller/scaffold_controller_generator.rb:24:in `block in <class:ScaffoldControllerGenerator>'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:274:in `instance_exec'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:274:in `block in _invoke_for_class_method'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/shell.rb:68:in `with_padding'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:133:in `_invoke_from_option_template_engine'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:115:in `invoke'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:277:in `block in _invoke_for_class_method'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/shell.rb:68:in `with_padding'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:266:in `_invoke_for_class_method'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:133:in `_invoke_from_option_scaffold_controller'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `each'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `map'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:133:in `invoke_all'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/group.rb:232:in `dispatch'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
	from /usr/local/bundle/gems/railties-5.1.0.beta1/lib/rails/generators.rb:269:in `invoke'
	from /usr/local/bundle/gems/railties-5.1.0.beta1/lib/rails/commands/generate/generate_command.rb:19:in `perform'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/bundle/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
	from /usr/local/bundle/gems/railties-5.1.0.beta1/lib/rails/command/base.rb:63:in `perform'
	from /usr/local/bundle/gems/railties-5.1.0.beta1/lib/rails/command.rb:44:in `invoke'
	from /usr/local/bundle/gems/railties-5.1.0.beta1/lib/rails/commands.rb:16:in `<top (required)>'
	from /var/www/fnix/bin/rails:4:in `require'
	from /var/www/fnix/bin/rails:4:in `<main>'
```

**Comment by clowder** [comment]
Ran into this today turns out it's a bug in the beta [that's now been fixed](https://github.com/rails/rails/commit/49d61aed4cc52b8c649f74d23781b3d3f6e01f41).

To fix it you can switch to master `gem 'rails', github: 'rails/rails'` or you'll have to wait for beta 2 to drop.

**Comment by syguer** [comment]
Rails 5.1 has been released. close this issue.
